// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuuZ-1XoYOyskbs66BhIYC7SlWqwcnKq0',
    appId: '1:197242003907:android:bd006352771a99e9cf1d76',
    messagingSenderId: '197242003907',
    projectId: 'curevia-f31a8',
    storageBucket: 'curevia-f31a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqBWyNLmamLpkXIFpLU9epevPwr4DFphg',
    appId: '1:197242003907:ios:5eb98205fc7070cecf1d76',
    messagingSenderId: '197242003907',
    projectId: 'curevia-f31a8',
    storageBucket: 'curevia-f31a8.firebasestorage.app',
    androidClientId: '197242003907-liqg29jp8ojak2h1riuc6q8ei92tscl0.apps.googleusercontent.com',
    iosClientId: '197242003907-stprgkmlou1h6k8q8t2p9sb0k2mt70lq.apps.googleusercontent.com',
    iosBundleId: 'com.example.curevia',
  );
}
